version: "3.9"
services:
  streamlit:
    container_name: "server_api"
    build:
      dockerfile: ./Dockerfile
      context: ./
# --- Porta local (funciona mesmo sem proxy) ---
    ports:
      - '8501:8501'

# --- Variáveis de ambiente (use "Env" no Portainer para preencher as ${...}) ---
  environment:
     OPENAI_API_KEY: ${OPENAI_API_KEY}
     OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4.1-mini}
     OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE:-0.2}
     OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS:-400}
     API_TOKEN: ${API_TOKEN}

    
    # --- Healthcheck ---
  healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3

  restart: unless-stopped